export const ADD_SUB_CLASS_REQUEST = "ADD_SUB_CLASS_REQUEST";
export const ADD_SUB_CLASS_SUCCESS = "ADD_SUB_CLASS_SUCCESS";
export const ADD_SUB_CLASS_FAILURE = "ADD_SUB_CLASS_FAILURE";

export const FETCH_SUB_CLASSES_REQUEST = "FETCH_SUB_CLASSES_REQUEST";
export const FETCH_SUB_CLASSES_SUCCESS = "FETCH_SUB_CLASSES_SUCCESS";
export const FETCH_SUB_CLASSES_FAILURE = "FETCH_SUB_CLASSES_FAILURE";

export const UPDATE_SUB_CLASS_REQUEST = "UPDATE_SUB_CLASS_REQUEST";
export const UPDATE_SUB_CLASS_SUCCESS = "UPDATE_SUB_CLASS_SUCCESS";
export const UPDATE_SUB_CLASS_FAILURE = "UPDATE_SUB_CLASS_FAILURE";

export const DELETE_SUB_CLASS_REQUEST = "DELETE_SUB_CLASS_REQUEST";
export const DELETE_SUB_CLASS_SUCCESS = "DELETE_SUB_CLASS_SUCCESS";
export const DELETE_SUB_CLASS_FAILURE = "DELETE_SUB_CLASS_FAILURE";
